// var h2 = document.querySelector('h2')
// var btn = document.querySelector('#btn')
// var a = 0;
// btn.addEventListener('click',function(){
//     a++;
//     h2.innerHTML = a;
// })



// let a = Math.random()*100
// let b = Math.floor(a);
// console.log(b);
// console.log("🤣");

// var btn = document.querySelector('button');
// var box = document.querySelector('.box2')
// // box.style.backgroundColor="red"
// btn.addEventListener('click', function(){
//     var a = Math.floor(Math.random()*256)
//     var b = Math.floor(Math.random()*256)
//     var c = Math.floor(Math.random()*256)
//     console.log(a,b,c);
//     box.style.backgroundColor = `rgb(${a},${b},${c})`
//     box.innerHTML = `rgb${a},${b},${c}`
// })


var arr = ["Aarav Sharma", "Aadi Sharma", "Aakash Sharma", "Aamir Sharma", "Aarush Sharma", "Abhay Sharma", "Abhinav Sharma", "Abhishek Sharma", "Adarsh Sharma", "Aditya Sharma", "Advait Sharma", "Agastya Sharma", "Ajay Sharma", "Akash Sharma", "Akshay Sharma", "Aman Sharma", "Amit Sharma", "Anand Sharma", "Aniket Sharma", "Anil Sharma", "Anirudh Sharma", "Ankit Sharma", "Anmol Sharma", "Ansh Sharma", "Anshul Sharma", "Anuj Sharma", "Arjun Sharma", "Arnav Sharma", "Aryan Sharma", "Ashish Sharma", "Ashok Sharma", "Atul Sharma", "Ayush Sharma", "Bharat Sharma", "Bhanu Sharma", "Chetan Sharma", "Chandan Sharma", "Chirag Sharma", "Darshan Sharma", "Deepak Sharma", "Dev Sharma", "Dhruv Sharma", "Dinesh Sharma", "Divyansh Sharma", "Gagan Sharma", "Gaurav Sharma", "Girish Sharma", "Harsh Sharma", "Himanshu Sharma", "Jatin Sharma", "Jay Sharma", "Jitesh Sharma", "Karan Sharma", "Kartik Sharma", "Keshav Sharma", "Krishna Sharma", "Kunal Sharma", "Lakshya Sharma", "Lokesh Sharma", "Madhav Sharma", "Mahir Sharma", "Manish Sharma", "Manoj Sharma", "Mayank Sharma", "Mohit Sharma", "Mohan Sharma", "Mukul Sharma", "Nakul Sharma", "Naman Sharma", "Naveen Sharma", "Neeraj Sharma", "Nikhil Sharma", "Nitin Sharma", "Om Sharma", "Parth Sharma", "Pankaj Sharma", "Piyush Sharma", "Prakash Sharma", "Pranav Sharma", "Prateek Sharma", "Raghav Sharma", "Rahul Sharma", "Raj Sharma", "Rajat Sharma", "Rajesh Sharma", "Rakesh Sharma", "Ravi Sharma", "Rishi Sharma", "Ritesh Sharma", "Rohan Sharma", "Rohit Sharma", "Sachin Sharma", "Sahil Sharma", "Sameer Sharma", "Samar Sharma", "Sandeep Sharma", "Sanjay Sharma", "Shivam Sharma", "Shubham Sharma", "Siddharth Sharma", "Sohan Sharma",

"Aarav Kashyap", "Aadi Kashyap", "Aakash Kashyap", "Aamir Kashyap", "Aarush Kashyap", "Abhay Kashyap", "Abhinav Kashyap", "Abhishek Kashyap", "Adarsh Kashyap", "Aditya Kashyap", "Advait Kashyap", "Agastya Kashyap", "Ajay Kashyap", "Akash Kashyap", "Akshay Kashyap", "Aman Kashyap", "Amit Kashyap", "Anand Kashyap", "Aniket Kashyap", "Anil Kashyap", "Anirudh Kashyap", "Ankit Kashyap", "Anmol Kashyap", "Ansh Kashyap", "Anshul Kashyap", "Anuj Kashyap", "Arjun Kashyap", "Arnav Kashyap", "Aryan Kashyap", "Ashish Kashyap", "Ashok Kashyap", "Atul Kashyap", "Ayush Kashyap", "Bharat Kashyap", "Bhanu Kashyap", "Chetan Kashyap", "Chandan Kashyap", "Chirag Kashyap", "Darshan Kashyap", "Deepak Kashyap", "Dev Kashyap", "Dhruv Kashyap", "Dinesh Kashyap", "Divyansh Kashyap", "Gagan Kashyap", "Gaurav Kashyap", "Girish Kashyap", "Harsh Kashyap", "Himanshu Kashyap", "Jatin Kashyap", "Jay Kashyap", "Jitesh Kashyap", "Karan Kashyap", "Kartik Kashyap", "Keshav Kashyap", "Krishna Kashyap", "Kunal Kashyap", "Lakshya Kashyap", "Lokesh Kashyap", "Madhav Kashyap", "Mahir Kashyap", "Manish Kashyap", "Manoj Kashyap", "Mayank Kashyap", "Mohit Kashyap", "Mohan Kashyap", "Mukul Kashyap", "Nakul Kashyap", "Naman Kashyap", "Naveen Kashyap", "Neeraj Kashyap", "Nikhil Kashyap", "Nitin Kashyap", "Om Kashyap", "Parth Kashyap", "Pankaj Kashyap", "Piyush Kashyap", "Prakash Kashyap", "Pranav Kashyap", "Prateek Kashyap", "Raghav Kashyap", "Rahul Kashyap", "Raj Kashyap", "Rajat Kashyap", "Rajesh Kashyap", "Rakesh Kashyap", "Ravi Kashyap", "Rishi Kashyap", "Ritesh Kashyap", "Rohan Kashyap", "Rohit Kashyap", "Sachin Kashyap", "Sahil Kashyap", "Sameer Kashyap", "Samar Kashyap", "Sandeep Kashyap", "Sanjay Kashyap", "Shivam Kashyap", "Shubham Kashyap", "Siddharth Kashyap", "Sohan Kashyap",

"Aarav Gupta", "Aadi Gupta", "Aakash Gupta", "Aamir Gupta", "Aarush Gupta", "Abhay Gupta", "Abhinav Gupta", "Abhishek Gupta", "Adarsh Gupta", "Aditya Gupta", "Advait Gupta", "Agastya Gupta", "Ajay Gupta", "Akash Gupta", "Akshay Gupta", "Aman Gupta", "Amit Gupta", "Anand Gupta", "Aniket Gupta", "Anil Gupta", "Anirudh Gupta", "Ankit Gupta", "Anmol Gupta", "Ansh Gupta", "Anshul Gupta", "Anuj Gupta", "Arjun Gupta", "Arnav Gupta", "Aryan Gupta", "Ashish Gupta", "Ashok Gupta", "Atul Gupta", "Ayush Gupta", "Bharat Gupta", "Bhanu Gupta", "Chetan Gupta", "Chandan Gupta", "Chirag Gupta", "Darshan Gupta", "Deepak Gupta", "Dev Gupta", "Dhruv Gupta", "Dinesh Gupta", "Divyansh Gupta", "Gagan Gupta", "Gaurav Gupta", "Girish Gupta", "Harsh Gupta", "Himanshu Gupta", "Jatin Gupta", "Jay Gupta", "Jitesh Gupta", "Karan Gupta", "Kartik Gupta", "Keshav Gupta", "Krishna Gupta", "Kunal Gupta", "Lakshya Gupta", "Lokesh Gupta", "Madhav Gupta", "Mahir Gupta", "Manish Gupta", "Manoj Gupta", "Mayank Gupta", "Mohit Gupta", "Mohan Gupta", "Mukul Gupta", "Nakul Gupta", "Naman Gupta", "Naveen Gupta", "Neeraj Gupta", "Nikhil Gupta", "Nitin Gupta", "Om Gupta", "Parth Gupta", "Pankaj Gupta", "Piyush Gupta", "Prakash Gupta", "Pranav Gupta", "Prateek Gupta", "Raghav Gupta", "Rahul Gupta", "Raj Gupta", "Rajat Gupta", "Rajesh Gupta", "Rakesh Gupta", "Ravi Gupta", "Rishi Gupta", "Ritesh Gupta", "Rohan Gupta", "Rohit Gupta", "Sachin Gupta", "Sahil Gupta", "Sameer Gupta", "Samar Gupta", "Sandeep Gupta", "Sanjay Gupta", "Shivam Gupta", "Shubham Gupta", "Siddharth Gupta", "Sohan Gupta",

"Aarav Verma", "Aadi Verma", "Aakash Verma", "Aamir Verma", "Aarush Verma", "Abhay Verma", "Abhinav Verma", "Abhishek Verma", "Adarsh Verma", "Aditya Verma", "Advait Verma", "Agastya Verma", "Ajay Verma", "Akash Verma", "Akshay Verma", "Aman Verma", "Amit Verma", "Anand Verma", "Aniket Verma", "Anil Verma", "Anirudh Verma", "Ankit Verma", "Anmol Verma", "Ansh Verma", "Anshul Verma", "Anuj Verma", "Arjun Verma", "Arnav Verma", "Aryan Verma", "Ashish Verma", "Ashok Verma", "Atul Verma", "Ayush Verma", "Bharat Verma", "Bhanu Verma", "Chetan Verma", "Chandan Verma", "Chirag Verma", "Darshan Verma", "Deepak Verma", "Dev Verma", "Dhruv Verma", "Dinesh Verma", "Divyansh Verma", "Gagan Verma", "Gaurav Verma", "Girish Verma", "Harsh Verma", "Himanshu Verma", "Jatin Verma", "Jay Verma", "Jitesh Verma", "Karan Verma", "Kartik Verma", "Keshav Verma", "Krishna Verma", "Kunal Verma", "Lakshya Verma", "Lokesh Verma", "Madhav Verma", "Mahir Verma", "Manish Verma", "Manoj Verma", "Mayank Verma", "Mohit Verma", "Mohan Verma", "Mukul Verma", "Nakul Verma", "Naman Verma", "Naveen Verma", "Neeraj Verma", "Nikhil Verma", "Nitin Verma", "Om Verma", "Parth Verma", "Pankaj Verma", "Piyush Verma", "Prakash Verma", "Pranav Verma", "Prateek Verma", "Raghav Verma", "Rahul Verma", "Raj Verma", "Rajat Verma", "Rajesh Verma", "Rakesh Verma", "Ravi Verma", "Rishi Verma", "Ritesh Verma", "Rohan Verma", "Rohit Verma", "Sachin Verma", "Sahil Verma", "Sameer Verma", "Samar Verma", "Sandeep Verma", "Sanjay Verma", "Shivam Verma", "Shubham Verma", "Siddharth Verma", "Sohan Verma",

"Aarav Singh", "Aadi Singh", "Aakash Singh", "Aamir Singh", "Aarush Singh", "Abhay Singh", "Abhinav Singh", "Abhishek Singh", "Adarsh Singh", "Aditya Singh", "Advait Singh", "Agastya Singh", "Ajay Singh", "Akash Singh", "Akshay Singh", "Aman Singh", "Amit Singh", "Anand Singh", "Aniket Singh", "Anil Singh", "Anirudh Singh", "Ankit Singh", "Anmol Singh", "Ansh Singh", "Anshul Singh", "Anuj Singh", "Arjun Singh", "Arnav Singh", "Aryan Singh", "Ashish Singh", "Ashok Singh", "Atul Singh", "Ayush Singh", "Bharat Singh", "Bhanu Singh", "Chetan Singh", "Chandan Singh", "Chirag Singh", "Darshan Singh", "Deepak Singh", "Dev Singh", "Dhruv Singh", "Dinesh Singh", "Divyansh Singh", "Gagan Singh", "Gaurav Singh", "Girish Singh", "Harsh Singh", "Himanshu Singh", "Jatin Singh", "Jay Singh", "Jitesh Singh", "Karan Singh", "Kartik Singh", "Keshav Singh", "Krishna Singh", "Kunal Singh", "Lakshya Singh", "Lokesh Singh", "Madhav Singh", "Mahir Singh", "Manish Singh", "Manoj Singh", "Mayank Singh", "Mohit Singh", "Mohan Singh", "Mukul Singh", "Nakul Singh", "Naman Singh", "Naveen Singh", "Neeraj Singh", "Nikhil Singh", "Nitin Singh", "Om Singh", "Parth Singh", "Pankaj Singh", "Piyush Singh", "Prakash Singh", "Pranav Singh", "Prateek Singh", "Raghav Singh", "Rahul Singh", "Raj Singh", "Rajat Singh", "Rajesh Singh", "Rakesh Singh", "Ravi Singh", "Rishi Singh", "Ritesh Singh", "Rohan Singh", "Rohit Singh", "Sachin Singh", "Sahil Singh", "Sameer Singh", "Samar Singh", "Sandeep Singh", "Sanjay Singh", "Shivam Singh", "Shubham Singh", "Siddharth Singh", "Sohan Singh",

"Aarav Yadav", "Aadi Yadav", "Aakash Yadav", "Aamir Yadav", "Aarush Yadav", "Abhay Yadav", "Abhinav Yadav", "Abhishek Yadav", "Adarsh Yadav", "Aditya Yadav", "Advait Yadav", "Agastya Yadav", "Ajay Yadav", "Akash Yadav", "Akshay Yadav", "Aman Yadav", "Amit Yadav", "Anand Yadav", "Aniket Yadav", "Anil Yadav", "Anirudh Yadav", "Ankit Yadav", "Anmol Yadav", "Ansh Yadav", "Anshul Yadav", "Anuj Yadav", "Arjun Yadav", "Arnav Yadav", "Aryan Yadav", "Ashish Yadav", "Ashok Yadav", "Atul Yadav", "Ayush Yadav", "Bharat Yadav", "Bhanu Yadav", "Chetan Yadav", "Chandan Yadav", "Chirag Yadav", "Darshan Yadav", "Deepak Yadav", "Dev Yadav", "Dhruv Yadav", "Dinesh Yadav", "Divyansh Yadav", "Gagan Yadav", "Gaurav Yadav", "Girish Yadav", "Harsh Yadav", "Himanshu Yadav", "Jatin Yadav", "Jay Yadav", "Jitesh Yadav", "Karan Yadav", "Kartik Yadav", "Keshav Yadav", "Krishna Yadav", "Kunal Yadav", "Lakshya Yadav", "Lokesh Yadav", "Madhav Yadav", "Mahir Yadav", "Manish Yadav", "Manoj Yadav", "Mayank Yadav", "Mohit Yadav", "Mohan Yadav", "Mukul Yadav", "Nakul Yadav", "Naman Yadav", "Naveen Yadav", "Neeraj Yadav", "Nikhil Yadav", "Nitin Yadav", "Om Yadav", "Parth Yadav", "Pankaj Yadav", "Piyush Yadav", "Prakash Yadav", "Pranav Yadav", "Prateek Yadav", "Raghav Yadav", "Rahul Yadav", "Raj Yadav", "Rajat Yadav", "Rajesh Yadav", "Rakesh Yadav", "Ravi Yadav", "Rishi Yadav", "Ritesh Yadav", "Rohan Yadav", "Rohit Yadav", "Sachin Yadav", "Sahil Yadav", "Sameer Yadav", "Samar Yadav", "Sandeep Yadav", "Sanjay Yadav", "Shivam Yadav", "Shubham Yadav", "Siddharth Yadav", "Sohan Yadav",

"Aarav Mishra", "Aadi Mishra", "Aakash Mishra", "Aamir Mishra", "Aarush Mishra", "Abhay Mishra", "Abhinav Mishra", "Abhishek Mishra", "Adarsh Mishra", "Aditya Mishra", "Advait Mishra", "Agastya Mishra", "Ajay Mishra", "Akash Mishra", "Akshay Mishra", "Aman Mishra", "Amit Mishra", "Anand Mishra", "Aniket Mishra", "Anil Mishra", "Anirudh Mishra", "Ankit Mishra", "Anmol Mishra", "Ansh Mishra", "Anshul Mishra", "Anuj Mishra", "Arjun Mishra", "Arnav Mishra", "Aryan Mishra", "Ashish Mishra", "Ashok Mishra", "Atul Mishra", "Ayush Mishra", "Bharat Mishra", "Bhanu Mishra", "Chetan Mishra", "Chandan Mishra", "Chirag Mishra", "Darshan Mishra", "Deepak Mishra", "Dev Mishra", "Dhruv Mishra", "Dinesh Mishra", "Divyansh Mishra", "Gagan Mishra", "Gaurav Mishra", "Girish Mishra", "Harsh Mishra", "Himanshu Mishra", "Jatin Mishra", "Jay Mishra", "Jitesh Mishra", "Karan Mishra", "Kartik Mishra", "Keshav Mishra", "Krishna Mishra", "Kunal Mishra", "Lakshya Mishra", "Lokesh Mishra", "Madhav Mishra", "Mahir Mishra", "Manish Mishra", "Manoj Mishra", "Mayank Mishra", "Mohit Mishra", "Mohan Mishra", "Mukul Mishra", "Nakul Mishra", "Naman Mishra", "Naveen Mishra", "Neeraj Mishra", "Nikhil Mishra", "Nitin Mishra", "Om Mishra", "Parth Mishra", "Pankaj Mishra", "Piyush Mishra", "Prakash Mishra", "Pranav Mishra", "Prateek Mishra", "Raghav Mishra", "Rahul Mishra", "Raj Mishra", "Rajat Mishra", "Rajesh Mishra", "Rakesh Mishra", "Ravi Mishra", "Rishi Mishra", "Ritesh Mishra", "Rohan Mishra", "Rohit Mishra", "Sachin Mishra", "Sahil Mishra", "Sameer Mishra", "Samar Mishra", "Sandeep Mishra", "Sanjay Mishra", "Shivam Mishra", "Shubham Mishra", "Siddharth Mishra", "Sohan Mishra",

"Aarav Agarwal", "Aadi Agarwal", "Aakash Agarwal", "Aamir Agarwal", "Aarush Agarwal", "Abhay Agarwal", "Abhinav Agarwal", "Abhishek Agarwal", "Adarsh Agarwal", "Aditya Agarwal", "Advait Agarwal", "Agastya Agarwal", "Ajay Agarwal", "Akash Agarwal", "Akshay Agarwal", "Aman Agarwal", "Amit Agarwal", "Anand Agarwal", "Aniket Agarwal", "Anil Agarwal", "Anirudh Agarwal", "Ankit Agarwal", "Anmol Agarwal", "Ansh Agarwal", "Anshul Agarwal", "Anuj Agarwal", "Arjun Agarwal", "Arnav Agarwal", "Aryan Agarwal", "Ashish Agarwal", "Ashok Agarwal", "Atul Agarwal", "Ayush Agarwal", "Bharat Agarwal", "Bhanu Agarwal", "Chetan Agarwal", "Chandan Agarwal", "Chirag Agarwal", "Darshan Agarwal", "Deepak Agarwal", "Dev Agarwal", "Dhruv Agarwal", "Dinesh Agarwal", "Divyansh Agarwal", "Gagan Agarwal", "Gaurav Agarwal", "Girish Agarwal", "Harsh Agarwal", "Himanshu Agarwal", "Jatin Agarwal", "Jay Agarwal", "Jitesh Agarwal", "Karan Agarwal", "Kartik Agarwal", "Keshav Agarwal", "Krishna Agarwal", "Kunal Agarwal", "Lakshya Agarwal", "Lokesh Agarwal", "Madhav Agarwal", "Mahir Agarwal", "Manish Agarwal", "Manoj Agarwal", "Mayank Agarwal", "Mohit Agarwal", "Mohan Agarwal", "Mukul Agarwal", "Nakul Agarwal", "Naman Agarwal", "Naveen Agarwal", "Neeraj Agarwal", "Nikhil Agarwal", "Nitin Agarwal", "Om Agarwal", "Parth Agarwal", "Pankaj Agarwal", "Piyush Agarwal", "Prakash Agarwal", "Pranav Agarwal", "Prateek Agarwal", "Raghav Agarwal", "Rahul Agarwal", "Raj Agarwal", "Rajat Agarwal", "Rajesh Agarwal", "Rakesh Agarwal", "Ravi Agarwal", "Rishi Agarwal", "Ritesh Agarwal", "Rohan Agarwal", "Rohit Agarwal", "Sachin Agarwal", "Sahil Agarwal", "Sameer Agarwal", "Samar Agarwal", "Sandeep Agarwal", "Sanjay Agarwal", "Shivam Agarwal", "Shubham Agarwal", "Siddharth Agarwal", "Sohan Agarwal",

"Aarav Tiwari", "Aadi Tiwari", "Aakash Tiwari", "Aamir Tiwari", "Aarush Tiwari", "Abhay Tiwari", "Abhinav Tiwari", "Abhishek Tiwari", "Adarsh Tiwari", "Aditya Tiwari", "Advait Tiwari", "Agastya Tiwari", "Ajay Tiwari", "Akash Tiwari", "Akshay Tiwari", "Aman Tiwari", "Amit Tiwari", "Anand Tiwari", "Aniket Tiwari", "Anil Tiwari", "Anirudh Tiwari", "Ankit Tiwari", "Anmol Tiwari", "Ansh Tiwari", "Anshul Tiwari", "Anuj Tiwari", "Arjun Tiwari", "Arnav Tiwari", "Aryan Tiwari", "Ashish Tiwari", "Ashok Tiwari", "Atul Tiwari", "Ayush Tiwari", "Bharat Tiwari", "Bhanu Tiwari", "Chetan Tiwari", "Chandan Tiwari", "Chirag Tiwari", "Darshan Tiwari", "Deepak Tiwari", "Dev Tiwari", "Dhruv Tiwari", "Dinesh Tiwari", "Divyansh Tiwari", "Gagan Tiwari", "Gaurav Tiwari", "Girish Tiwari", "Harsh Tiwari", "Himanshu Tiwari", "Jatin Tiwari", "Jay Tiwari", "Jitesh Tiwari", "Karan Tiwari", "Kartik Tiwari", "Keshav Tiwari", "Krishna Tiwari", "Kunal Tiwari", "Lakshya Tiwari", "Lokesh Tiwari", "Madhav Tiwari", "Mahir Tiwari", "Manish Tiwari", "Manoj Tiwari", "Mayank Tiwari", "Mohit Tiwari", "Mohan Tiwari", "Mukul Tiwari", "Nakul Tiwari", "Naman Tiwari", "Naveen Tiwari", "Neeraj Tiwari", "Nikhil Tiwari", "Nitin Tiwari", "Om Tiwari", "Parth Tiwari", "Pankaj Tiwari", "Piyush Tiwari", "Prakash Tiwari", "Pranav Tiwari", "Prateek Tiwari", "Raghav Tiwari", "Rahul Tiwari", "Raj Tiwari", "Rajat Tiwari", "Rajesh Tiwari", "Rakesh Tiwari", "Ravi Tiwari", "Rishi Tiwari", "Ritesh Tiwari", "Rohan Tiwari", "Rohit Tiwari", "Sachin Tiwari", "Sahil Tiwari", "Sameer Tiwari", "Samar Tiwari", "Sandeep Tiwari", "Sanjay Tiwari", "Shivam Tiwari", "Shubham Tiwari", "Siddharth Tiwari", "Sohan Tiwari",

"Aarav Pandey", "Aadi Pandey", "Aakash Pandey", "Aamir Pandey", "Aarush Pandey", "Abhay Pandey", "Abhinav Pandey", "Abhishek Pandey", "Adarsh Pandey", "Aditya Pandey", "Advait Pandey", "Agastya Pandey", "Ajay Pandey", "Akash Pandey", "Akshay Pandey", "Aman Pandey", "Amit Pandey", "Anand Pandey", "Aniket Pandey", "Anil Pandey", "Anirudh Pandey", "Ankit Pandey", "Anmol Pandey", "Ansh Pandey", "Anshul Pandey", "Anuj Pandey", "Arjun Pandey", "Arnav Pandey", "Aryan Pandey", "Ashish Pandey", "Ashok Pandey", "Atul Pandey", "Ayush Pandey", "Bharat Pandey", "Bhanu Pandey", "Chetan Pandey", "Chandan Pandey", "Chirag Pandey", "Darshan Pandey", "Deepak Pandey", "Dev Pandey", "Dhruv Pandey", "Dinesh Pandey", "Divyansh Pandey", "Gagan Pandey", "Gaurav Pandey", "Girish Pandey", "Harsh Pandey", "Himanshu Pandey", "Jatin Pandey", "Jay Pandey", "Jitesh Pandey", "Karan Pandey", "Kartik Pandey", "Keshav Pandey", "Krishna Pandey", "Kunal Pandey", "Lakshya Pandey", "Lokesh Pandey", "Madhav Pandey", "Mahir Pandey", "Manish Pandey", "Manoj Pandey", "Mayank Pandey", "Mohit Pandey", "Mohan Pandey", "Mukul Pandey", "Nakul Pandey", "Naman Pandey", "Naveen Pandey", "Neeraj Pandey", "Nikhil Pandey", "Nitin Pandey", "Om Pandey", "Parth Pandey", "Pankaj Pandey", "Piyush Pandey", "Prakash Pandey", "Pranav Pandey", "Prateek Pandey", "Raghav Pandey", "Rahul Pandey", "Raj Pandey", "Rajat Pandey", "Rajesh Pandey", "Rakesh Pandey", "Ravi Pandey", "Rishi Pandey", "Ritesh Pandey", "Rohan Pandey", "Rohit Pandey", "Sachin Pandey", "Sahil Pandey", "Sameer Pandey", "Samar Pandey", "Sandeep Pandey", "Sanjay Pandey", "Shivam Pandey", "Shubham Pandey", "Siddharth Pandey", "Sohan Pandey"];

// console.log(arr);
// console.log(arr.length);
// var a = Math.floor(Math.random()*arr.length)
// console.log(arr[a]);

for(let i = 0; i <arr.length; i++){
    console.log(arr[i]);
    
}






